WITH REC AS (
    SELECT 
        R.HRCD_PERIODO_RECAUDO AS "Periodo",
        R.ASO_IDENTIFICACION_ASOCIADO AS "Id",
        SUM(R.HRCD_VALOR_RECAUDO) AS "Valor_Recaudado_Total"
    FROM GRC.GCC_HISTORIA_RECAUDO R
    INNER JOIN GRC.GCC_CONCEPTO C ON R.CON_CODIGO = C.CON_CODIGO
    WHERE C.AGE_CODIGO = 3
        AND R.HRCD_PERIODO_RECAUDO = ?
        AND R.ASO_IDENTIFICACION_ASOCIADO IN ({ids})
        AND R.HRCD_NRO_TRANSACCION NOT IN ('71','52','51')
    GROUP BY R.HRCD_PERIODO_RECAUDO, R.ASO_IDENTIFICACION_ASOCIADO
),
FAC AS (
    SELECT
        F.HFR_PERIODO_FACT AS "Periodo",
        F.ASO_IDENTIFICACION AS "Id",
        SUM(F.HFR_VALOR_CUOTA_MES_CALCULADO) AS "Cuota_Mes",
        SUM(F.HFR_VALOR_VENCIDO_CALCULADO) AS "Vencido_Mes"
    FROM GRC.GCC_HIST_FACT_RECAUDO F
    WHERE F.AGE_NOMBRE = 'COOMEVA'
        AND F.HFR_PERIODO_FACT = ?
        AND F.ASO_IDENTIFICACION IN ({ids})
    GROUP BY F.HFR_PERIODO_FACT, F.ASO_IDENTIFICACION
)
SELECT
    COALESCE(FAC."Periodo", REC."Periodo") AS "Periodo",
    COALESCE(FAC."Id", REC."Id")           AS "Id",
    FAC."Cuota_Mes",
    FAC."Vencido_Mes",
    REC."Valor_Recaudado_Total"
FROM FAC
FULL OUTER JOIN REC
    ON FAC."Periodo" = REC."Periodo"
    AND FAC."Id"     = REC."Id";