SELECT 
    CAST(TO_CHAR(GES_FECHA_GESTION, 'YYYYMM') AS NUMBER) AS "Periodo",
    ASO_IDENTIFICACION AS "Id",
    ACT_ACTOR_GESTION AS "Actor_gestion",
    ACC_NOMBRE_ACCION AS "Accion",
    RES_NOMBRE_RESPUESTA AS "Respuesta"
FROM GRC.GCC_HISTORIA_GESTIONES
WHERE
    ASO_IDENTIFICACION IN ({ids})
    AND TRUNC(GES_FECHA_GESTION) BETWEEN TO_DATE('?', 'DD/MM/YYYY') 
                                     AND LAST_DAY(TO_DATE('?', 'DD/MM/YYYY'))