SELECT 
    CAST(TO_CHAR(GES_FECHA_GESTION, 'YYYYMM') AS NUMBER) AS "strPeriodo",
    ASO_IDENTIFICACION AS "strIdentificacion",
    ACT_ACTOR_GESTION AS "Actor_gestion",
    ACC_NOMBRE_ACCION AS "Accion",
    RES_NOMBRE_RESPUESTA AS "Respuesta"
FROM GRC.GCC_HISTORIA_GESTIONES
WHERE
    ASO_IDENTIFICACION IN ({IDS})
    AND TRUNC(GES_FECHA_GESTION) BETWEEN TO_DATE(:periodo_foto,'YYYY-MM-DD')
                                     AND LAST_DAY(TO_DATE(:periodo_foto,'YYYY-MM-DD'))